### ISSUE TITLE
Error when trying to Make

### ISSUE THREAD

**Issue by gowithefloww** [anthill/open-moulinette#14]
Got an error when trying to make : 

```
\open-molinette-insee\insee>make
process_begin: CreateProcess<NULL, rm -rf data, ...> failed.
make >e=2>: Le fichier spécifié est introuvable.
make : **[download] Erreur 2
```

Might be my bad, running on Win7 and using GnuWin to makefile.

**Comment by armgilles** [comment]
Hi FloSugar, 

I'm running on mac so i can't reproduce this error... But in \open-molinette-insee\insee, is there a directory "data" ? some files inside ?

**Comment by vallettea** [comment]
The `Makefile` was designed for unix machines so commands like `mkdir` won't work. As @armgilles says, you should check if there is a `data` directory.

**Comment by gowithefloww** [comment]
Hey there,
Nope, there isn't any data directory indeed. So I should use an unix machine to be able to make ?

**Comment by vallettea** [comment]
try to create a directory called data inside open-moulinette and edit to makefile to remove the lines with data and retry

**Comment by gowithefloww** [comment]
That's exactly what I tried, I also removed all the comments beginning by "#" which were returning some errors but even the `@wget` and `@unzip`  seem not to run on windows. Still returning the same error.

**Comment by vallettea** [comment]
humm try to install both wget and unzip but if it doesn’t work just consider installing linux on a partition, windows sucks 

Alexandre ValletteANTS
Founder 

+33 6 71 35 89 43

@vallettea

**Comment by gowithefloww** [comment]
yup, I'll run it on an unix machine :-)

Thanks for helping anyway - and for your work.

EDIT  : Just did, it works smoothly!
