### ISSUE TITLE
add more recent years ?

### ISSUE THREAD

**Issue by AlexisEidelman** [anthill/open-moulinette#24]
There is a new edition of data.
http://www.insee.fr/fr/themes/detail.asp?reg_id=99&ref_id=revenu-pauvrete-menage

But I can't see any Iris anymore. Do you know anything about it ?

**Comment by armgilles** [comment]
[Population census 2012 is out](http://www.insee.fr/fr/bases-de-donnees/default.asp?page=recensement/resultats/2012/donnees-detaillees-recensement-2012.htm) (just saw it). For Iris, it only "Bases de données infracommunales" files unfortunately...

It could be good to add them !
Now i wonder if we had to replace the old one (2011) or add the new one. If we add 2012, we have to change all feature's name : 
- "NB_B101" -> "NB_B101_2011" & we create an others for 2012 "NB_B101_2012".

It's more work but offer more data and nice features (increase between 2011 -> 2012).

I'll try to check it this week end. Have you some ideas ?

**Comment by armgilles** [comment]
Done PR #29

I update documentation too.
