### ISSUE TITLE
missing NB_F116

### ISSUE THREAD

**Issue by AlexisEidelman** [anthill/open-moulinette#25]
in https://github.com/anthill/open-moulinette/blob/master/insee/mk_data.py ?
You know these insee files better than I do but I suggest to use 
   `[x for x in df.columns if x[:5] == 'NB_F1' and len(x) == 7]`
instead of an explicit list

**Comment by armgilles** [comment]
Good point. I fix it and this is way more Pythonic !

Thanks :)
