### ISSUE TITLE
Use reduced coordinates in CAF folder

### ISSUE THREAD

**Issue by bleucitron** [anthill/open-moulinette#32]
The `CAF` folder seems to generate files with lat-lon coordinates (`geo_point_2d` and `geo_shape`) with 10+ decimals of precision.

8 decimals (about 1mm) is more than enough is most cases.
http://gis.stackexchange.com/questions/8650/how-to-measure-the-accuracy-of-latitude-and-longitude

You should check how much size you can spare by keeping only 8 decimals in your coordinates.

**Comment by armgilles** [comment]
Original output : 108 Mo
New output : 99 Mo
