### ISSUE TITLE
Mention license?

### ISSUE THREAD

**Issue by thbar** [anthill/open-moulinette#35]
Is your license MIT or something else? It would be great to mention this in the repository, but I cannot find the information. Thanks!

**Comment by DavidBruant** [comment]
Yes, MIT Licence. 
https://github.com/anthill/open-moulinette/blob/master/LICENSE
Sorry for the omission. Thanks for the issue!

**Comment by thbar** [comment]
Great, thanks! :+1:  (and thanks for your work)
