### ISSUE TITLE
extraction territoriale

### ISSUE THREAD

**Issue by akakeronos** [anthill/open-moulinette#37]
Bonjour,

Serait-il possible d'extraire les données qui concernent un territoire en particulier en donnant comme argument un code département ou région au script ?

Pascal

**Comment by armgilles** [comment]
Bonjour Pascal, 

sur quelle jeux de données tu as besoin de cette feature ?

**Comment by akakeronos** [comment]
Salut Armand,
Par exemple sur les données de l'INSEE.
Pascal

**Comment by armgilles** [comment]
Une fois que tu as exécuté le script tu peux filtrer le département ou la région sur les champs "REG" et "DEP".

**Comment by armgilles** [comment]
Je close l'issue si c'est réglé. Dans le cas contraire, n'hésites pas à la ré-ouvrir.
