### ISSUE TITLE
données du REI

### ISSUE THREAD

**Issue by AlexisEidelman** [anthill/open-moulinette#45]
Les éléments d'imposition à la fiscalité locale

[Lien vers les fichiers](https://www.data.gouv.fr/fr/datasets/impots-locaux-fichier-de-recensement-des-elements-dimposition-a-la-fiscalite-directe-locale-rei-3/)

**Comment by armgilles** [comment]
Je viens de regarder un peu les fichiers.

Pour le rendu final, je pense faire un .csv qui contient l'ensemble des 3 fichiers (2013/2014 et 2015).

Comme chaque fichier possède plus ou moins 800 variables, cela fera un fichier de 36 k lignes (nombre de communes en France) x 3*800 variables.

On prend uniquement les variables lié aux éléments d'imposition afin d'éviter la répétition des variables géographiques (nom de la commune etc...).

**Nommage des variables :** 

- ```B00``` (FNB - FRAIS DASSIETTE, DEGREVEMENT, NON VALEURS) sera renommer ```B00_YY``` (selon l'année du fichier).
   --> ```BOO_13```, ```BOO_14```, ```BOO_15``` et ainsi de suite pour l'ensemble des variables.

Le merge se fera sur la variable ```IDCOM``` qui semble unique pour identifier une commune.

Qu'est ce que tu en pense @AlexisEidelman ?

Edit : Cette analyse sera aussi dans un répertoire indépendant de open-moulinette.

Edit2 : Les 3 fichiers n'ont pas le même nombre de variables (hors variables géographique) : 
 - 2013 : 772
 - 2014 : 765
 - 2015 : 794

exemple : ```WD40MGL``` est dans le fichier de 2015 mais absent des autres fichiers

Il y a sur l'ensemble des fichiers 848 variables différentes (dont une grande majorité seront multipliée par l'année du fichier).

**Comment by armgilles** [comment]
ping @AlexisEidelman
