### ISSUE TITLE
[insee-iris] Bad coordinates for DOM TOM

### ISSUE THREAD

**Issue by armgilles** [anthill/open-moulinette#5]
I take some random points in DOM TOM to compare with _insee-iris_'s results : 
- Saint-Barthélemy : 
  - Gmap : 17.899002, -62.828300
  - result : 2.707392005397649, 6.285960550950626
- Guadeloupe : 
  - Gmap : 16.264087, -61.574302
  - result : 2.705883719869279, 6.28458848768047
- Guyanne : 
  *Gmap : 5.153908, -52.650181
  *result : 0.5049460534121631, -2.239479666101393
- Réunion : 
  - Gmap : -20.898175, 55.483693
  - result : -2.5290937943850196, 56.11702466964122

**Comment by armgilles** [comment]
It seems, there are bad projection with proj4. If we refer to this [datums](http://professionnels.ign.fr/sites/default/files/DC_DL_Contours-Iris_2-0.pdf)

![capture d ecran 2015-05-06 a 09 39 08 2](https://cloud.githubusercontent.com/assets/8374843/7489159/e73cf8c6-f3d3-11e4-98a5-9dc5cef05325.png)
- for Guadeloupe, Saint-Barthélemy, Saint-Martin, Martinique : [EPSG:32620](http://spatialreference.org/ref/epsg/32620/)
- for Guyane : [EPSG:2972](http://spatialreference.org/ref/epsg/2972/)
- for Réunion : [EPSG:2975](http://spatialreference.org/ref/epsg/2975/) 

Maybe some bad data ?

For example Guyane is near to Africa : 

![capture d ecran 2015-05-06 a 09 44 28](https://cloud.githubusercontent.com/assets/8374843/7489209/a1105e46-f3d4-11e4-9d1e-7e00095994cb.png)

**Comment by vallettea** [comment]
Yes it's weird. We should point this out to IGN.

**Comment by armgilles** [comment]
Fix with https://github.com/anthill/open-moulinette/pull/6
