### ISSUE TITLE
Fichier de sortie csv

### ISSUE THREAD

**Issue by goudrix** [anthill/open-moulinette#52]
Bonjour,

Disposant d'un environnement Windows, et étant assez peu familier avec le script et l'usage qu'il en est fait, est-il possible de récupérer directement le fichier qui concatène les données de l'Insee (output.csv 750 Mo) ?

Je vous remercie.

**Comment by armgilles** [comment]
Bonjour @goudrix , nous ne stockons le fichier.

Mais je pense qu'il est possible sur un env windows de pouvoir faire tourner le script.
